FROM alpine:edge


WORKDIR /data
WORKDIR /config

EXPOSE 1704
EXPOSE 1705
EXPOSE 1780

RUN apk add librespot --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
RUN apk add shairport-sync --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
RUN apk -U add bash snapcast

# # Need to run `sh /start.sh` on server start manually
# RUN apk add alpine-sdk
# RUN apk add wget
# # RUN mkdir /home/shairport-sync && cd /home/shairport-sync && wget https://git.alpinelinux.org/aports/plain/testing/shairport-sync/APKBUILD && wget https://git.alpinelinux.org/aports/plain/testing/shairport-sync/shairport-sync.initd
# RUN adduser -D myuser abuild
# RUN adduser myuser abuild
# USER myuser
# RUN mkdir ~/shairport-sync
# COPY ./shairport-sync/APKBUILD /home/myuser/shairport-sync/APKBUILD
# COPY ./shairport-sync/shairport-sync.initd /home/myuser/shairport-sync/shairport-sync.initd
# RUN ls ~/shairport-sync | echo
# RUN cd ~/shairport-sync && abuild-keygen -a -n
# USER root
# RUN cp /home/myuser/.abuild/* /etc/apk/keys/
# USER myuser
# RUN cd ~/shairport-sync && abuild -r
# USER root
# RUN apk add /home/myuser/packages/myuser/x86_64/*.apk --allow-untrusted 

COPY ./config/snapserver.conf /etc
COPY ./start.sh /
RUN chmod +x /start.sh
ENTRYPOINT [ "/start.sh" ]